    -- Drop tables if they exist to ensure a clean start (optional but safer for init)
    DROP TABLE IF EXISTS items CASCADE;
    DROP TABLE IF EXISTS users CASCADE;

    -- Create users table first due to foreign key dependency
    CREATE TABLE users (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username VARCHAR(50) NOT NULL UNIQUE,
        email VARCHAR(255) NOT NULL UNIQUE,
        password VARCHAR(255) NOT NULL,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    -- Create items table
    CREATE TABLE items (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title VARCHAR(100) NOT NULL,
        description VARCHAR(1000) NOT NULL,
        category VARCHAR(50) NOT NULL,
        status VARCHAR(255) NOT NULL CHECK (status IN ('LOST','FOUND')),
        image_path VARCHAR(255),
        image_file_id VARCHAR(255), -- Added field for ImageKit File ID
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        user_id BIGINT NOT NULL,
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE -- Added ON DELETE CASCADE
    );

    -- Optional: Indexes for faster lookups
    CREATE INDEX idx_items_status ON items (status);
    CREATE INDEX idx_items_category ON items (category);
    

